#ifndef STYLES_H

#define STYLES_H

#include <windows.h>

//styles
#define STL_BUTTON (WS_VISIBLE | WS_CHILD | BS_MULTILINE)
#define STL_COMBO (WS_VISIBLE | WS_CHILD | WS_VSCROLL | CBS_DROPDOWNLIST)
#define STL_TEXT (WS_VISIBLE | WS_CHILD)
#define STL_TEXT_RIGHT (WS_VISIBLE | WS_CHILD | SS_RIGHT)
#define STL_TEXT_CENTER (WS_VISIBLE | WS_CHILD | SS_CENTER)
#define STL_EDIT (WS_VISIBLE | WS_CHILD | WS_BORDER)
#define STL_LIST (WS_VISIBLE | WS_CHILD | LBS_NOTIFY)
#define STL_RADIO (WS_VISIBLE | WS_CHILD | BS_RADIOBUTTON)

#endif
